# Generated by Django 5.1.7 on 2025-03-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0002_skills_created_at_skills_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('project_image', models.ImageField(upload_to='project_image/')),
                ('priject_Desc', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(to='Base_app.skills')),
            ],
        ),
    ]
