# Generated by Django 5.1.7 on 2025-03-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='priject_Desc',
            new_name='project_Desc',
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='skill', to='Base_app.skills'),
        ),
    ]
