# Generated by Django 5.1.7 on 2025-05-01 06:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0004_rename_priject_desc_project_project_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='project_image'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
